Bit Manipulation adding code for Question 03, 04
DimpleOrg/InterviewDS pull request #46
Opened 2018-12-03 12:37 UTC by anilhariparamhans

2018-12-04 01:20 UTC, dimplenaresh1 requested changes

2018-12-04 01:20 UTC, dimplenaresh1 commented on CrackingCodingInterview/vAnil/05 Bit Manipulation/03 FlipBitToWin/FlipBitToWin.cpp
> +MY03FLIPBITTOWIN_API int Longest1Sequence(unsigned num)
can we use size_t.

2018-12-06 15:22 UTC, anilhariparamhans commented on CrackingCodingInterview/vAnil/05 Bit Manipulation/03 FlipBitToWin/FlipBitToWin.cpp
> +MY03FLIPBITTOWIN_API int Longest1Sequence(unsigned num)
Incorporated this review comment.

2018-12-09 13:13 UTC, dimplenaresh1 approved these changes

2018-12-09 13:15 UTC, merged